
name: Build Windows Installer

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install
        env:
          # Evita descargar binarios innecesarios durante la instalación
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1

      - name: Build React App & Electron
        # Forzamos la descarga del binario de Electron justo antes de compilar
        run: |
          npx electron-builder install-app-deps
          npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PizzaDiRoma-Installer
          path: release/*.exe
          if-no-files-found: error
